import { Injectable, Logger } from '@nestjs/common';
import { AiReportStatus, TranslationStatus } from '@prisma/client';
import { looksChinese } from '../ai/language.util';
import { PrismaService } from '../prisma/prisma.service';

export type MaintenanceResult = {
  /** DONE AiReports whose content is not Chinese → marked FAILED (regenerated by GENERATE jobs). */
  englishReportsFailed: number;
  /** NewsArticle.summaryZh not Chinese → cleared + aiSummaryStatus PENDING. */
  englishNewsSummariesReset: number;
  /** translatedContentZh not Chinese → cleared + translationStatus NONE. */
  englishTranslationsReset: number;
  /** Snippet-era translations on articles that now carry a full body → cleared so re-translation covers全文. */
  snippetTranslationsReset: number;
};

const BATCH = 500;

/**
 * One-shot data repairs for rows persisted before the router's language gate /
 * full-body translation existed. Marking English reports FAILED (instead of
 * deleting) keeps the audit trail and makes `runReportIfChanged`'s latest-DONE
 * lookup miss them, so the next GENERATE run regenerates every affected
 * analysis; readers only surface DONE reports, so English content disappears
 * from the site immediately.
 */
@Injectable()
export class DataMaintenanceService {
  private readonly logger = new Logger(DataMaintenanceService.name);

  constructor(private readonly prisma: PrismaService) {}

  async resetNonChineseContent(): Promise<MaintenanceResult> {
    const englishReportsFailed = await this.failEnglishReports();
    const englishNewsSummariesReset = await this.resetEnglishNewsSummaries();
    const englishTranslationsReset = await this.resetEnglishTranslations();
    const snippetTranslationsReset = await this.resetSnippetTranslations();
    const result = {
      englishReportsFailed,
      englishNewsSummariesReset,
      englishTranslationsReset,
      snippetTranslationsReset,
    };
    this.logger.log(`Maintenance reset-non-chinese: ${JSON.stringify(result)}`);
    return result;
  }

  private async failEnglishReports(): Promise<number> {
    let failed = 0;
    let cursor: string | undefined;
    for (;;) {
      const rows = await this.prisma.aiReport.findMany({
        where: { status: AiReportStatus.DONE, content: { not: null } },
        select: { id: true, content: true },
        orderBy: { id: 'asc' },
        take: BATCH,
        ...(cursor ? { skip: 1, cursor: { id: cursor } } : {}),
      });
      if (rows.length === 0) break;
      cursor = rows[rows.length - 1].id;
      const englishIds = rows
        .filter((r) => r.content && !looksChinese(r.content))
        .map((r) => r.id);
      if (englishIds.length > 0) {
        const res = await this.prisma.aiReport.updateMany({
          where: { id: { in: englishIds } },
          data: {
            status: AiReportStatus.FAILED,
            errorMessage: 'maintenance: output was not Chinese; queued for regeneration',
          },
        });
        failed += res.count;
      }
      if (rows.length < BATCH) break;
    }
    return failed;
  }

  private async resetEnglishNewsSummaries(): Promise<number> {
    const rows = await this.prisma.newsArticle.findMany({
      where: { summaryZh: { not: null } },
      select: { id: true, summaryZh: true },
    });
    const ids = rows.filter((r) => r.summaryZh && !looksChinese(r.summaryZh)).map((r) => r.id);
    if (ids.length === 0) return 0;
    const res = await this.prisma.newsArticle.updateMany({
      where: { id: { in: ids } },
      data: { summaryZh: null, aiSummaryStatus: AiReportStatus.PENDING },
    });
    return res.count;
  }

  private async resetEnglishTranslations(): Promise<number> {
    const rows = await this.prisma.newsArticle.findMany({
      where: { translatedContentZh: { not: null } },
      select: { id: true, translatedContentZh: true },
    });
    const ids = rows
      .filter((r) => r.translatedContentZh && !looksChinese(r.translatedContentZh))
      .map((r) => r.id);
    if (ids.length === 0) return 0;
    const res = await this.prisma.newsArticle.updateMany({
      where: { id: { in: ids } },
      data: { translatedContentZh: null, translationStatus: TranslationStatus.NONE },
    });
    return res.count;
  }

  /**
   * Translations produced before full bodies were stored only cover the trail
   * snippet. Once the article has a body (backfilled by FETCH_NEWS), clear the
   * short translation so the premium re-translate button produces 重點整理 +
   * 全文翻譯. Full-text translations are recognizable by the「全文翻譯」section
   * header the new instruction emits.
   */
  /**
   * Queues every article for re-classification and removes duplicate titles.
   * Existing rows predate the `isWorldCupRelated` relevance gate, so flipping
   * them to PENDING makes the next GENERATE_NEWS_SUMMARY runs re-classify each
   * one and delete off-topic articles (other sports / club gossip that merely
   * mention "World Cup"). summaryZh is kept until overwritten so the site
   * never shows empty summaries mid-cleanup.
   */
  async requeueNewsClassification(): Promise<{
    duplicatesRemoved: number;
    requeued: number;
  }> {
    const duplicatesRemoved = await this.removeDuplicateTitles();
    const res = await this.prisma.newsArticle.updateMany({
      where: { aiSummaryStatus: { not: AiReportStatus.PENDING } },
      data: { aiSummaryStatus: AiReportStatus.PENDING },
    });
    this.logger.log(
      `Maintenance requeue-news: duplicatesRemoved=${duplicatesRemoved} requeued=${res.count}`,
    );
    return { duplicatesRemoved, requeued: res.count };
  }

  /** Deletes newer copies of articles sharing the same (case-folded) title. */
  private async removeDuplicateTitles(): Promise<number> {
    const rows = await this.prisma.newsArticle.findMany({
      select: { id: true, titleEn: true },
      orderBy: { createdAt: 'asc' },
    });
    const seen = new Set<string>();
    const dupes: string[] = [];
    for (const r of rows) {
      const key = r.titleEn.trim().toLowerCase();
      if (seen.has(key)) dupes.push(r.id);
      else seen.add(key);
    }
    if (dupes.length === 0) return 0;
    const [, deleted] = await this.prisma.$transaction([
      this.prisma.aiReport.deleteMany({
        where: { entityType: 'NEWS', entityId: { in: dupes } },
      }),
      this.prisma.newsArticle.deleteMany({ where: { id: { in: dupes } } }),
    ]);
    return deleted.count;
  }

  private async resetSnippetTranslations(): Promise<number> {
    const rows = await this.prisma.newsArticle.findMany({
      where: {
        translationStatus: TranslationStatus.DONE,
        translatedContentZh: { not: null },
        contentEn: { not: null },
      },
      select: { id: true, translatedContentZh: true },
    });
    const ids = rows
      .filter((r) => !(r.translatedContentZh ?? '').includes('全文翻譯'))
      .map((r) => r.id);
    if (ids.length === 0) return 0;
    const res = await this.prisma.newsArticle.updateMany({
      where: { id: { in: ids } },
      data: { translatedContentZh: null, translationStatus: TranslationStatus.NONE },
    });
    return res.count;
  }
}
